a=input('digite algo: ')
print('qual e a classe? ', type(a))
print('e composto por espacos? ', a.isspace())
print('e composto por numeros? ', a.isnumeric())
print('esta em maiusulas? ', a.isupper())
print('esta em minusculas? ', a.islower())
print('esta capitalizada? ', a.istitle())
print('e alfanumerico? ', a.isalnum())
print('e alfabetico? ', a.isalpha())