print('ola, seja bem vindo!')
val = input('digite um valor inteiro com 4 digitos: ')
print(f'Analisando o numero {val}')
print(f'unidade: {val[3]}')
print(f'dezena: {val[-2]} ')
print(f'centena: {val[-3]} ')
print(f'milhar: {val[-4]}' )